name: Release Clipy

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build App
        run: |
          xcodebuild -scheme Clipy \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            clean build

      - name: Ad-hoc Sign
        run: |
          codesign --force --deep --sign - build/Build/Products/Release/Clipy.app

      - name: Compress App
        run: |
          cd build/Build/Products/Release
          zip -r Clipy.app.zip Clipy.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Clipy.app
          path: build/Build/Products/Release/Clipy.app.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Build/Products/Release/Clipy.app.zip
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'nightly' }}
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'Nightly Build' }}
          draft: false
          prerelease: false
